### ISSUE TITLE
Should Transformers subclasses exist for specific configurations?

### ISSUE THREAD

**Issue by csala** [sdv-dev/RDT#243]
We currently have several `Transformers` that accept parameters that modify their behavior.

For example, the `CategoricalTransformer` can be configured to be `fuzzy` or not, the `NumericalTransformer` can be configured to learn the `min_value`, `max_value` and `rounding` level, and the `DatetimeTransformer` can be configured to `strip_constant` and round the values to the same units as the input.

So the question here is: Should we create sub-classes of each one of these Transformers pinning the `__init__` parameters to some specific values, so they can also be used as classes without arguments?

Maybe not every parameter needs to be fixed in the subclasses, but at least the ones that produce very different behaviors.

For example, for the Transformers mentioned above, we could create:
* `CategoricalFuzzyTransformer`: Equivalent to `CategoricalTransformer(fuzzy=True)`
* `NumericalBoundedTransformer`: Equivalent `NumericalTransformer(min_value='auto', max_value='auto', rounding='auto')`
* `DatetimeRoundedTransformer`: Equivalent to `DatetimeTransformer(strip_constant=True)`

**Comment by fealho** [comment]
@csala I don't think there are many other combinations that would be commonly used, since we plan to remove the `NullTransformer` from the available arguments. The available parameters that we could change for each transformer are:

- `CategoricalTransformer`: `fuzzy` and `clip`. I don't think `clip` matters is sufficiently to have it's own subclass, so the only subclass here should be the `CategoricalFuzzyTransformer`.
- `OneHotEncodingTransformer`:  `error_on_unknown`. Again, I don't think this matters too much.
- `LabelEncodingTransformer` and `BooleanTransformer`: they have no arguments.
- `DatetimeTransformer`: `strip_constant`. Since this is the only parameter and it's a boolean, we only need to create a `DatetimeRoundedTransformer`.
- `GaussianCopulaTransformer`: `dtype` and `distribution`. Since `dtype` doesn't matter much, and creating a subclass for all values of `distribution` seems overkill, I don't think we should create any subclasses here.
- `NumericalTransformer`: `dtype`, `rounding`, `min_value` and `max_value`. Since `dtype` doesn't matter, and `min_value`/`max_value` are similar (so they they should have the same value in a subclass), that leaves us with 3 potential subclasses, `NumericalBounded` for the min/max values as `auto`, `NumericalRoundedTransformer` for rounding, and `NumericalRoundedBoundedTransfomer` for both.

All of the suggested subclasses here will be implemented in the PR #260.
