### ISSUE TITLE
Categorical transformer is not composition identity when fuzzy is enabled

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/RDT#278]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: v0.5.2
* Python version: 3.8
* Operating System: MacOS 11.6

### Error Description

When transforming and reverse_transforming with the CategoricalTransformer, if the `fuzzy` option is enabled, we do not always get the same input data after reverse_transform. This is because, sometimes the input value is transformed to be a float within another category's range, after applying the Gaussian noise.

We should determine if this is the desired behavior. We could consider clipping the transformed values to the category range, or replacing it with the mean value of the category if it goes out of bounds.

**Comment by npatki** [comment]
Confirming that this is desired behavior. When we noise the data:
- The values may go out-of-bounds for the range. This happens with low probability (since the noise is Gaussian).
- We correctly return that the composition identity is `False` if we notice that there is the `add_noise` parameter ([see line](https://github.com/sdv-dev/RDT/blob/master/rdt/transformers/categorical.py#L70)).

In practice, this is ok because we don't expect users to reverse transform the same data that they forward transform. The reversed data will be new, model created data (eg. synthetic data).

We applied the same principle to the `FloatFormatter` when `model_missing_values=False` (we randomly add them back in).

@amontanez24 FYI
