### ISSUE TITLE
BayesGMMTransformer does not work for pandas.Dataframe

### ISSUE THREAD

**Issue by hacen3064** [sdv-dev/RDT#485]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: 0.6.4
* Python version:3.7
* Operating System:Linux

### Error Description

If I call the fit method of the ```BayesGMMTransformer``` on a ```pandas.DataFrame``` with more than one column I get the following error : ``` 'DataFrame' object has no attribute 'dtype' ```.

### Steps to reproduce

```
import pandas as pd
import numpy as np
from rdt.transformers import BayesGMMTransformer

transformer = BayesGMMTransformer()
random_data = np.random.rand(100,2)
data = pd.DataFrame(data=random_data, columns=['col1', 'col2'])

transformer.fit(data, columns = ['col1', 'col2'])
```

The traceback leads to the line 135 in the fit method of the class ```NumericalTransformer``` in ```numerical.py```
the line is: **self._dtype = self.dtype or data.dtype**
which should be **self._dtype = self.dtype or data.dtypes** for pandas.DataFrame

**Comment by npatki** [comment]
Hi @hacen3064, thanks for the detailed code & explanation. The `BayesGMMTransformer` is only meant to be fit and used on 1 column. Your code would work if you only fit to a single column.
```python
transformer.fit(data, columns=['col1'])
```

If you are trying to fit multiple columns, then the intended usage is through the `HyperTransformer` which manages different transformers for each individual column.

I understand it's confusing due to the plural keyword `columns`. In the upcoming release, we'll be fixing this as well as providing more documentation about how to use the transformers.

Let me know if you have any questions!

**Comment by hacen3064** [comment]
Got it. Thank you very much.
